version: '2.18'

volumes:
  pg_db_weather:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - ./pg_db_weather:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
