# Generated by Django 4.2.3 on 2023-09-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.IntegerField(max_length=20)),
                ('temp', models.FloatField(max_length=15)),
                ('pressure', models.IntegerField(blank=True, max_length=15, null=True)),
                ('humidity', models.IntegerField(blank=True, max_length=15, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_set', to='cities.city')),
            ],
        ),
    ]
